[supervisord]
nodaemon=false
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:miner]
command=/opt/venv/bin/python /opt/miner.py
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/miner.log
stderr_logfile=/var/log/supervisor/miner_error.log
redirect_stderr=true